  spring:
      datasource:
        username: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        password: postgres
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: NCA
            jdbc:
              lob:
                non_contextual_creation: 'true'
        hibernate: