ALTER TABLE comments
ALTER COLUMN creation_date SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE comments
ALTER COLUMN last_edit_date SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE news
ALTER COLUMN creation_date SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE news
ALTER COLUMN last_edit_date SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ALTER COLUMN creation_date SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ALTER COLUMN last_edit_date SET DEFAULT CURRENT_TIMESTAMP;